#! /usr/bin/env python

# Software License Agreement (BSD License)
#
# Copyright (c) 2013, Eric Perko
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the     above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the names of the authors nor the names of their
#    affiliated organizations may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import serial
import socket               # Import socket module
import os                   #import libraries necessary for running the ifconfigg.sh file
import sys
import libnmea_navsat_driver.driver
import numpy as np
import rospy
import tf
import time
from datetime import datetime
from sensor_msgs.msg import Imu
from geometry_msgs.msg import PoseStamped
from geometry_msgs.msg import TwistStamped

if __name__ == '__main__':
    rospy.init_node('nmea_tcp_driver')

    imu_pub = rospy.Publisher("gps_imu", Imu, queue_size=5)
    imu_pose_pub = rospy.Publisher("gps_imu_pose", PoseStamped, queue_size=5)
    vel_pub = rospy.Publisher("gps_vel", TwistStamped, queue_size=5)

    s = socket.socket()         # Create a socket object
    host = rospy.get_param('~host', '192.168.1.100')
    port = rospy.get_param('~port', 5018)

    s.connect((host, port))
    print "Device Connected"
    # frame_id = libnmea_navsat_driver.driver.RosNMEADriver.get_frame_id()
    frame_id = "gnss_trimble"

    while not rospy.is_shutdown():
        GPS = s.recv(1024)
        data = GPS.strip()    
        split = data.split()
        
    GPS.close           #Close GPS socket when done
